### ISSUE TITLE
Dead repository link?

### ISSUE THREAD

**Issue by phoenixhell** [eu-digital-green-certificates/dgc-api-tests#3]
## Dead repository link?

* Source File: /Installation.md
* Line(s): 45
* Question:
The git clone mentions a repository URL (https://github.com/corona-warn-app/cwa-pytest-apitest), which is not accessible by me. Could it be that the repository was renamed, moved or deleted?

Sadly I don't have the knowledge to evaluate or fix this, so I'm documenting it as an issue.

**Comment by daniel-eder** [comment]
@phoenixhell that seems to be a copy paste issue - please use https://github.com/eu-digital-green-certificates/dgc-api-tests.git as the clone URL (and cd into the directory it creates), the remainder of the instructions should then work

**Comment by daniel-eder** [comment]
Closed in https://github.com/eu-digital-green-certificates/dgc-api-tests/commit/d4a6f673425d19bdde76c6282767f74ce63162a8
